app:
    resource: "@AppBundle/Resources/config/routing.yaml"
    prefix: /

user:
    resource: "@UserBundle/Resources/config/routing.yaml"
    prefix: /

movie:
    resource: "@MovieBundle/Resources/config/routing.yaml"
    prefix: /
