
admin_movie_import:
    resource: "@MovieBundle/Resources/config/routing/admin/_entrypoint.yaml"
    prefix: /admin
    defaults:
        _format: 'html'

public_movie_import:
    resource: "@MovieBundle/Resources/config/routing/public/_entrypoint.yaml"
    prefix: /public
    defaults:
        _format: 'html'
