admin_app_import:
    resource: "@AppBundle/Resources/config/routing/admin/_entrypoint.yaml"
    prefix: /admin
    defaults:
        _format: "html"

main_app_import:
    resource: "@AppBundle/Resources/config/routing/main/_entrypoint.yaml"
    prefix: /
    defaults:
        _format: "html"
